# Test Docker Compose Configuration
# Simple setup for testing containerized application

version: '3.8'

services:
  # Relay Server
  relay-server:
    image: proof-messenger-relay:test
    container_name: proof-messenger-relay-test
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - BIND_ADDRESS=0.0.0.0:8080
    networks:
      - proof-messenger-test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Web Application
  web-app:
    image: proof-messenger-web:test
    container_name: proof-messenger-web-test
    ports:
      - "80:80"
    depends_on:
      relay-server:
        condition: service_healthy
    networks:
      - proof-messenger-test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  proof-messenger-test:
    driver: bridge