[package]
name = "proof-messenger-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
proof-messenger-protocol = { path = "../proof-messenger-protocol" }
clap = { version = "4.0.32", features = ["derive"] }